# FLUTTERWAVE_PUBLIC_KEY = ENV['FLUTTERWAVE_PUBLIC_KEY']
# FLUTTERWAVE_SECRET_KEY = ENV['FLUTTERWAVE_SECRET_KEY']
# FLUTTERWAVE_ENCRYPTION_KEY = ENV['FLUTTERWAVE_ENCRYPTION_KEY']

# $payment = Flutterwave.new(FLUTTERWAVE_PUBLIC_KEY, FLUTTERWAVE_SECRET_KEY, FLUTTERWAVE_ENCRYPTION_KEY)